FROM nvcr.io/nvidia/tensorrt:22.10-py3
ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY ./install.sh /install.sh
COPY ./requirements.txt /requirements.txt
WORKDIR /
RUN bash install.sh
